#include "license_dialog.h"

calibmar::LicenseDialog::LicenseDialog(QWidget* parent) {
  setWindowTitle("License");
  QVBoxLayout* layout = new QVBoxLayout(this);
  QTextEdit* text_edit = new QTextEdit(this);

  QString licenses;
  licenses += "<h2>Calibmar</h2>";
  licenses += CalibmarLicense();
  licenses += "<h2>External</h2>";
  licenses += "<h3>Ceres Solver</h3>";
  licenses += CeresLicense();
  licenses += "<h3>OpenCV</h3>";
  licenses += OpenCVLicense();
  licenses += "<h3>Qt</h3>";
  licenses += QtLicense();
  licenses += "<h3>COLMAP</h3>";
  licenses += COLMAPLicense();
  // COLMAP transitive licenses
  licenses += "<h4>FLANN</h4>";
  licenses += FLANNLicense();
  licenses += "<h4>Graclus</h4>";
  licenses += GraclusLicense();
  licenses += "<h4>LSD</h4>";
  licenses += LSDLicense();
  licenses += "<h4>PBA</h4>";
  licenses += PBALicense();
  licenses += "<h4>PoissonRecon</h4>";
  licenses += PoissonReconLicense();
  licenses += "<h4>SiftGPU</h4>";
  licenses += SiftGPULicense();
  licenses += "<h4>SQLite</h4>";
  licenses += SQLiteLicense();
  licenses += "<h4>VLFeat</h4>";
  licenses += VLFeatLicense();

  text_edit->setHtml(licenses);

  layout->addWidget(text_edit);
}

QString calibmar::LicenseDialog::CalibmarLicense() {
  const QString license =
      "Copyright (c) 2024, Kiel University.<br>"
      "All rights reserved.<br>"
      "<br>"
      "Redistribution and use in source and binary forms, with or without<br>"
      "modification, are permitted provided that the following conditions are "
      "met:<br>"
      "<br>"
      "    * Redistributions of source code must retain the above copyright<br>"
      "      notice, this list of conditions and the following disclaimer.<br>"
      "<br>"
      "    * Redistributions in binary form must reproduce the above "
      "copyright<br>"
      "      notice, this list of conditions and the following disclaimer in "
      "the<br>"
      "      documentation and/or other materials provided with the "
      "distribution.<br>"
      "<br>"
      "    * Neither the name of the copyright holder nor the names "
      "of<br>"
      "      its contributors may be used to endorse or promote products "
      "derived<br>"
      "      from this software without specific prior written permission.<br>"
      "<br>"
      "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "
      "\"AS IS\"<br>"
      "AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, "
      "THE<br>"
      "IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR "
      "PURPOSE<br>"
      "ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS "
      "BE<br>"
      "LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR<br>"
      "CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF<br>"
      "SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR "
      "BUSINESS<br>"
      "INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER "
      "IN<br>"
      "CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR "
      "OTHERWISE)<br>"
      "ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF "
      "THE<br>"
      "POSSIBILITY OF SUCH DAMAGE.<br>"
      "<br>";
  return license;
}

QString calibmar::LicenseDialog::COLMAPLicense() {
  const QString license =
      "Copyright (c) 2018, ETH Zurich and UNC Chapel Hill.<br>"
      "All rights reserved.<br>"
      "<br>"
      "Redistribution and use in source and binary forms, with or without<br>"
      "modification, are permitted provided that the following conditions are "
      "met:<br>"
      "<br>"
      "    * Redistributions of source code must retain the above copyright<br>"
      "      notice, this list of conditions and the following disclaimer.<br>"
      "<br>"
      "    * Redistributions in binary form must reproduce the above "
      "copyright<br>"
      "      notice, this list of conditions and the following disclaimer in "
      "the<br>"
      "      documentation and/or other materials provided with the "
      "distribution.<br>"
      "<br>"
      "    * Neither the name of ETH Zurich and UNC Chapel Hill nor the names "
      "of<br>"
      "      its contributors may be used to endorse or promote products "
      "derived<br>"
      "      from this software without specific prior written permission.<br>"
      "<br>"
      "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "
      "\"AS IS\"<br>"
      "AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, "
      "THE<br>"
      "IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR "
      "PURPOSE<br>"
      "ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS "
      "BE<br>"
      "LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR<br>"
      "CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF<br>"
      "SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR "
      "BUSINESS<br>"
      "INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER "
      "IN<br>"
      "CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR "
      "OTHERWISE)<br>"
      "ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF "
      "THE<br>"
      "POSSIBILITY OF SUCH DAMAGE.<br>"
      "<br>"
      "Author: Johannes L. Schoenberger (jsch-at-demuc-dot-de)";
  return license;
}

QString calibmar::LicenseDialog::FLANNLicense() {
  const QString license =
      "The BSD License<br>"
      "<br>"
      "Copyright (c) 2008-2011  Marius Muja (mariusm@cs.ubc.ca). "
      "All rights reserved.<br>"
      "Copyright (c) 2008-2011  David G. Lowe (lowe@cs.ubc.ca). "
      "All rights reserved.<br>"
      "<br>"
      "Redistribution and use in source and binary forms, with or without<br>"
      "modification, are permitted provided that the following conditions<br>"
      "are met:<br>"
      "<br>"
      " * Redistributions of source code must retain the above copyright<br>"
      "   notice, this list of conditions and the following disclaimer.<br>"
      " * Redistributions in binary form must reproduce the above copyright<br>"
      "   notice, this list of conditions and the following disclaimer in<br>"
      "   the documentation and/or other materials provided with the<br>"
      "   distribution.<br>"
      " * Neither the name of the \"University of British Columbia\" nor<br>"
      "   the names of its contributors may be used to endorse or promote<br>"
      "   products derived from this software without specific prior<br>"
      "   written permission.<br>"
      "<br>"
      "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS<br>"
      "\"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT<br>"
      "LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS<br>"
      "FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE<br>"
      "COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,<br>"
      "INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES<br>"
      "(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS<br>"
      "OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS<br>"
      "INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,<br>"
      "WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE<br>"
      "OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,<br>"
      "EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.";
  return license;
}

QString calibmar::LicenseDialog::GraclusLicense() {
  const QString license =
      "Copyright(c) 2008 Brian Kulis, Yuqiang Guan (version 1.2)<br>"
      "This program is free software: you can redistribute it and/or modify<br>"
      "it under the terms of the GNU General Public License as published by<br>"
      "the Free Software Foundation, either version 3 of the License, or<br>"
      "(at your option) any later version.<br><br>"
      "This program is distributed in the hope that it will be useful,<br>"
      "but WITHOUT ANY WARRANTY; without even the implied warranty of<br>"
      "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the<br>"
      "GNU General Public License for more details.<br><br>"
      "You should have received a copy of the GNU General Public License<br>"
      "along with this program.  If not, see http://www.gnu.org/licenses/.";
  return license;
}

QString calibmar::LicenseDialog::LSDLicense() {
  const QString license =
      "LSD - Line Segment Detector on digital images<br>"
      "<br>"
      "This code is part of the following publication and was subject<br>"
      "to peer review:"
      "<br>"
      "  \"LSD: a Line Segment Detector\" by Rafael Grompone von Gioi,<br>"
      "  Jeremie Jakubowicz, Jean-Michel Morel, and Gregory Randall,<br>"
      "  Image Processing On Line, 2012. DOI:10.5201/ipol.2012.gjmr-lsd<br>"
      "  http://dx.doi.org/10.5201/ipol.2012.gjmr-lsd<br>"
      "<br>"
      "Copyright(c) 2007-2011 rafael grompone von gioi <grompone@gmail.com><br>"
      "<br>"
      "This program is free software: you can redistribute it and/or<br>"
      "modify it under the terms of the GNU Affero General Public License<br>"
      "as published by the Free Software Foundation, either version 3 of<br>"
      "the License, or (at your option) any later version.<br>"
      "<br>"
      "This program is distributed in the hope that it will be useful,<br>"
      "but WITHOUT ANY WARRANTY; without even the implied warranty of<br>"
      "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the<br>"
      "GNU Affero General Public License for more details.<br>"
      "<br>"
      "You should have received a copy of the GNU Affero General Public<br>"
      "License along with this program.<br>"
      "If not, see http://www.gnu.org/licenses/.";
  return license;
}

QString calibmar::LicenseDialog::PBALicense() {
  const QString license =
      "Copyright (c) 2011  Changchang Wu (ccwu@cs.washington.edu)<br>"
      "and the University of Washington at Seattle<br>"
      "<br>"
      "This library is free software; you can redistribute it and/or<br>"
      "modify it under the terms of the GNU General Public<br>"
      "License as published by the Free Software Foundation; either<br>"
      "Version 3 of the License, or (at your option) any later version.<br>"
      "<br>"
      "This library is distributed in the hope that it will be useful,<br>"
      "but WITHOUT ANY WARRANTY; without even the implied warranty of<br>"
      "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU<br>"
      "General Public License for more details.";
  return license;
}

QString calibmar::LicenseDialog::PoissonReconLicense() {
  const QString license =
      "The MIT License (MIT)<br>"
      "<br>"
      "Copyright (c) 2015 mkazhdan<br>"
      "<br>"
      "Permission is hereby granted, free of charge, to any person<br>"
      "obtaining a copy of this software and associated documentation<br>"
      "files (the \"Software\"), to deal in the Software without<br>"
      "restriction, including without limitation the rights to use, copy,<br>"
      "modify, merge, publish, distribute, sublicense, and/or sell copies<br>"
      "of the Software, and to permit persons to whom the Software is<br>"
      "furnished to do so, subject to the following conditions:<br>"
      "<br>"
      "The above copyright notice and this permission notice shall be<br>"
      "included in all copies or substantial portions of the Software.<br>"
      "<br>"
      "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,<br>"
      "EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF<br>"
      "MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND<br>"
      "NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS<br>"
      "BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN<br>"
      "ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN<br>"
      "CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE<br>"
      "SOFTWARE.";
  return license;
}

QString calibmar::LicenseDialog::SiftGPULicense() {
  const QString license =
      "Copyright (c) 2007 University of North Carolina at Chapel Hill<br>"
      "All Rights Reserved<br>"
      "<br>"
      "Permission to use, copy, modify and distribute this software and its<br>"
      "documentation for educational, research and non-profit purposes,<br>"
      "without fee, and without a written agreement is hereby granted,<br>"
      "provided that the above copyright notice and the following paragraph<br>"
      "appear in all copies.<br>"
      "<br>"
      "The University of North Carolina at Chapel Hill make no<br>"
      "representations about the suitability of this software for any<br>"
      "purpose. It is provided 'as is' without express or implied warranty.";
  return license;
}

QString calibmar::LicenseDialog::SQLiteLicense() {
  const QString license =
      "The author disclaims copyright to this source code. In place of<br>"
      "a legal notice, here is a blessing:<br>"
      "May you do good and not evil.<br>"
      "May you find forgiveness for yourself and forgive others.<br>"
      "May you share freely, never taking more than you give.";
  return license;
}

QString calibmar::LicenseDialog::VLFeatLicense() {
  const QString license =
      "Copyright (C) 2007-11, Andrea Vedaldi and Brian Fulkerson<br>"
      "Copyright (C) 2012-13, The VLFeat Team<br>"
      "All rights reserved.<br>"
      "<br>"
      "Redistribution and use in source and binary forms, with or without<br>"
      "modification, are permitted provided that the following conditions <br>"
      "are met:<br>"
      "1. Redistributions of source code must retain the above copyright<br>"
      "   notice, this list of conditions and the following disclaimer.<br>"
      "2. Redistributions in binary form must reproduce the above copyright<br>"
      "   notice, this list of conditions and the following disclaimer in<br>"
      "   the documentation and/or other materials provided with the<br>"
      "   distribution.<br>"
      "<br>"
      "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS<br>"
      "AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT<br>"
      "LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS<br>"
      "FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE<br>"
      "COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,<br>"
      "INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,<br>"
      "BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;<br>"
      "LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER<br>"
      "CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT<br>"
      "LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN<br>"
      "ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE<br>"
      "POSSIBILITY OF SUCH DAMAGE.";
  return license;
}

QString calibmar::LicenseDialog::CeresLicense() {
  const QString license =
      "Ceres Solver - A fast non-linear least squares minimizer<br>"
      "Copyright 2015 Google Inc. All rights reserved.<br>"
      "http://ceres-solver.org/<br>"
      "<br>"
      "Redistribution and use in source and binary forms, with or without<br>"
      "modification, are permitted provided that the following conditions are met:<br>"
      "<br>"
      "* Redistributions of source code must retain the above copyright notice,<br>"
      "  this list of conditions and the following disclaimer.<br>"
      "* Redistributions in binary form must reproduce the above copyright notice,<br>"
      "  this list of conditions and the following disclaimer in the documentation<br>"
      "  and/or other materials provided with the distribution.<br>"
      "* Neither the name of Google Inc. nor the names of its contributors may be<br>"
      "  used to endorse or promote products derived from this software without<br>"
      "  specific prior written permission.<br>"
      "<br>"
      "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"<br>"
      "AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE<br>"
      "IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE<br>"
      "ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE<br>"
      "LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR<br>"
      "CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF<br>"
      "SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS<br>"
      "INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN<br>"
      "CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)<br>"
      "ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE<br>"
      "POSSIBILITY OF SUCH DAMAGE.<br>";
  return license;
}

QString calibmar::LicenseDialog::OpenCVLicense() {
  const QString license =

      "                                 Apache License<br>"
      "                           Version 2.0, January 2004<br>"
      "                        http://www.apache.org/licenses/<br>"
      "<br>"
      "   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION<br>"
      "<br>"
      "   1. Definitions.<br>"
      "<br>"
      "      \"License\" shall mean the terms and conditions for use, reproduction,<br>"
      "      and distribution as defined by Sections 1 through 9 of this document.<br>"
      "<br>"
      "      \"Licensor\" shall mean the copyright owner or entity authorized by<br>"
      "      the copyright owner that is granting the License.<br>"
      "<br>"
      "      \"Legal Entity\" shall mean the union of the acting entity and all<br>"
      "      other entities that control, are controlled by, or are under common<br>"
      "      control with that entity. For the purposes of this definition,<br>"
      "      \"control\" means (i) the power, direct or indirect, to cause the<br>"
      "      direction or management of such entity, whether by contract or<br>"
      "      otherwise, or (ii) ownership of fifty percent (50%) or more of the<br>"
      "      outstanding shares, or (iii) beneficial ownership of such entity.<br>"
      "<br>"
      "      \"You\" (or \"Your\") shall mean an individual or Legal Entity<br>"
      "      exercising permissions granted by this License.<br>"
      "<br>"
      "      \"Source\" form shall mean the preferred form for making modifications,<br>"
      "      including but not limited to software source code, documentation<br>"
      "      source, and configuration files.<br>"
      "<br>"
      "      \"Object\" form shall mean any form resulting from mechanical<br>"
      "      transformation or translation of a Source form, including but<br>"
      "      not limited to compiled object code, generated documentation,<br>"
      "      and conversions to other media types.<br>"
      "<br>"
      "      \"Work\" shall mean the work of authorship, whether in Source or<br>"
      "      Object form, made available under the License, as indicated by a<br>"
      "      copyright notice that is included in or attached to the work<br>"
      "      (an example is provided in the Appendix below).<br>"
      "<br>"
      "      \"Derivative Works\" shall mean any work, whether in Source or Object<br>"
      "      form, that is based on (or derived from) the Work and for which the<br>"
      "      editorial revisions, annotations, elaborations, or other modifications<br>"
      "      represent, as a whole, an original work of authorship. For the purposes<br>"
      "      of this License, Derivative Works shall not include works that remain<br>"
      "      separable from, or merely link (or bind by name) to the interfaces of,<br>"
      "      the Work and Derivative Works thereof.<br>"
      "<br>"
      "      \"Contribution\" shall mean any work of authorship, including<br>"
      "      the original version of the Work and any modifications or additions<br>"
      "      to that Work or Derivative Works thereof, that is intentionally<br>"
      "      submitted to Licensor for inclusion in the Work by the copyright owner<br>"
      "      or by an individual or Legal Entity authorized to submit on behalf of<br>"
      "      the copyright owner. For the purposes of this definition, \"submitted\"<br>"
      "      means any form of electronic, verbal, or written communication sent<br>"
      "      to the Licensor or its representatives, including but not limited to<br>"
      "      communication on electronic mailing lists, source code control systems,<br>"
      "      and issue tracking systems that are managed by, or on behalf of, the<br>"
      "      Licensor for the purpose of discussing and improving the Work, but<br>"
      "      excluding communication that is conspicuously marked or otherwise<br>"
      "      designated in writing by the copyright owner as \"Not a Contribution.\"<br>"
      "<br>"
      "      \"Contributor\" shall mean Licensor and any individual or Legal Entity<br>"
      "      on behalf of whom a Contribution has been received by Licensor and<br>"
      "      subsequently incorporated within the Work.<br>"
      "<br>"
      "   2. Grant of Copyright License. Subject to the terms and conditions of<br>"
      "      this License, each Contributor hereby grants to You a perpetual,<br>"
      "      worldwide, non-exclusive, no-charge, royalty-free, irrevocable<br>"
      "      copyright license to reproduce, prepare Derivative Works of,<br>"
      "      publicly display, publicly perform, sublicense, and distribute the<br>"
      "      Work and such Derivative Works in Source or Object form.<br>"
      "<br>"
      "   3. Grant of Patent License. Subject to the terms and conditions of<br>"
      "      this License, each Contributor hereby grants to You a perpetual,<br>"
      "      worldwide, non-exclusive, no-charge, royalty-free, irrevocable<br>"
      "      (except as stated in this section) patent license to make, have made,<br>"
      "      use, offer to sell, sell, import, and otherwise transfer the Work,<br>"
      "      where such license applies only to those patent claims licensable<br>"
      "      by such Contributor that are necessarily infringed by their<br>"
      "      Contribution(s) alone or by combination of their Contribution(s)<br>"
      "      with the Work to which such Contribution(s) was submitted. If You<br>"
      "      institute patent litigation against any entity (including a<br>"
      "      cross-claim or counterclaim in a lawsuit) alleging that the Work<br>"
      "      or a Contribution incorporated within the Work constitutes direct<br>"
      "      or contributory patent infringement, then any patent licenses<br>"
      "      granted to You under this License for that Work shall terminate<br>"
      "      as of the date such litigation is filed.<br>"
      "<br>"
      "   4. Redistribution. You may reproduce and distribute copies of the<br>"
      "      Work or Derivative Works thereof in any medium, with or without<br>"
      "      modifications, and in Source or Object form, provided that You<br>"
      "      meet the following conditions:<br>"
      "<br>"
      "      (a) You must give any other recipients of the Work or<br>"
      "          Derivative Works a copy of this License; and<br>"
      "<br>"
      "      (b) You must cause any modified files to carry prominent notices<br>"
      "          stating that You changed the files; and<br>"
      "<br>"
      "      (c) You must retain, in the Source form of any Derivative Works<br>"
      "          that You distribute, all copyright, patent, trademark, and<br>"
      "          attribution notices from the Source form of the Work,<br>"
      "          excluding those notices that do not pertain to any part of<br>"
      "          the Derivative Works; and<br>"
      "<br>"
      "      (d) If the Work includes a \"NOTICE\" text file as part of its<br>"
      "          distribution, then any Derivative Works that You distribute must<br>"
      "          include a readable copy of the attribution notices contained<br>"
      "          within such NOTICE file, excluding those notices that do not<br>"
      "          pertain to any part of the Derivative Works, in at least one<br>"
      "          of the following places: within a NOTICE text file distributed<br>"
      "          as part of the Derivative Works; within the Source form or<br>"
      "          documentation, if provided along with the Derivative Works; or,<br>"
      "          within a display generated by the Derivative Works, if and<br>"
      "          wherever such third-party notices normally appear. The contents<br>"
      "          of the NOTICE file are for informational purposes only and<br>"
      "          do not modify the License. You may add Your own attribution<br>"
      "          notices within Derivative Works that You distribute, alongside<br>"
      "          or as an addendum to the NOTICE text from the Work, provided<br>"
      "          that such additional attribution notices cannot be construed<br>"
      "          as modifying the License.<br>"
      "<br>"
      "      You may add Your own copyright statement to Your modifications and<br>"
      "      may provide additional or different license terms and conditions<br>"
      "      for use, reproduction, or distribution of Your modifications, or<br>"
      "      for any such Derivative Works as a whole, provided Your use,<br>"
      "      reproduction, and distribution of the Work otherwise complies with<br>"
      "      the conditions stated in this License.<br>"
      "<br>"
      "   5. Submission of Contributions. Unless You explicitly state otherwise,<br>"
      "      any Contribution intentionally submitted for inclusion in the Work<br>"
      "      by You to the Licensor shall be under the terms and conditions of<br>"
      "      this License, without any additional terms or conditions.<br>"
      "      Notwithstanding the above, nothing herein shall supersede or modify<br>"
      "      the terms of any separate license agreement you may have executed<br>"
      "      with Licensor regarding such Contributions.<br>"
      "<br>"
      "   6. Trademarks. This License does not grant permission to use the trade<br>"
      "      names, trademarks, service marks, or product names of the Licensor,<br>"
      "      except as required for reasonable and customary use in describing the<br>"
      "      origin of the Work and reproducing the content of the NOTICE file.<br>"
      "<br>"
      "   7. Disclaimer of Warranty. Unless required by applicable law or<br>"
      "      agreed to in writing, Licensor provides the Work (and each<br>"
      "      Contributor provides its Contributions) on an \"AS IS\" BASIS,<br>"
      "      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or<br>"
      "      implied, including, without limitation, any warranties or conditions<br>"
      "      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A<br>"
      "      PARTICULAR PURPOSE. You are solely responsible for determining the<br>"
      "      appropriateness of using or redistributing the Work and assume any<br>"
      "      risks associated with Your exercise of permissions under this License.<br>"
      "<br>"
      "   8. Limitation of Liability. In no event and under no legal theory,<br>"
      "      whether in tort (including negligence), contract, or otherwise,<br>"
      "      unless required by applicable law (such as deliberate and grossly<br>"
      "      negligent acts) or agreed to in writing, shall any Contributor be<br>"
      "      liable to You for damages, including any direct, indirect, special,<br>"
      "      incidental, or consequential damages of any character arising as a<br>"
      "      result of this License or out of the use or inability to use the<br>"
      "      Work (including but not limited to damages for loss of goodwill,<br>"
      "      work stoppage, computer failure or malfunction, or any and all<br>"
      "      other commercial damages or losses), even if such Contributor<br>"
      "      has been advised of the possibility of such damages.<br>"
      "<br>"
      "   9. Accepting Warranty or Additional Liability. While redistributing<br>"
      "      the Work or Derivative Works thereof, You may choose to offer,<br>"
      "      and charge a fee for, acceptance of support, warranty, indemnity,<br>"
      "      or other liability obligations and/or rights consistent with this<br>"
      "      License. However, in accepting such obligations, You may act only<br>"
      "      on Your own behalf and on Your sole responsibility, not on behalf<br>"
      "      of any other Contributor, and only if You agree to indemnify,<br>"
      "      defend, and hold each Contributor harmless for any liability<br>"
      "      incurred by, or claims asserted against, such Contributor by reason<br>"
      "      of your accepting any such warranty or additional liability.<br>"
      "<br>"
      "   END OF TERMS AND CONDITIONS<br>"
      "<br>"
      "   APPENDIX: How to apply the Apache License to your work.<br>"
      "<br>"
      "      To apply the Apache License to your work, attach the following<br>"
      "      boilerplate notice, with the fields enclosed by brackets \"[]\"<br>"
      "      replaced with your own identifying information. (Don't include<br>"
      "      the brackets!)  The text should be enclosed in the appropriate<br>"
      "      comment syntax for the file format. We also recommend that a<br>"
      "      file or class name and description of purpose be included on the<br>"
      "      same \"printed page\" as the copyright notice for easier<br>"
      "      identification within third-party archives.<br>"
      "<br>"
      "   Copyright [yyyy] [name of copyright owner]<br>"
      "<br>"
      "   Licensed under the Apache License, Version 2.0 (the \"License\");<br>"
      "   you may not use this file except in compliance with the License.<br>"
      "   You may obtain a copy of the License at<br>"
      "<br>"
      "       http://www.apache.org/licenses/LICENSE-2.0<br>"
      "<br>"
      "   Unless required by applicable law or agreed to in writing, software<br>"
      "   distributed under the License is distributed on an \"AS IS\" BASIS,<br>"
      "   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.<br>"
      "   See the License for the specific language governing permissions and<br>"
      "   limitations under the License.<br>";
  return license;
}

QString calibmar::LicenseDialog::QtLicense() {
  const QString license =
      " GNU LESSER GENERAL PUBLIC LICENSE<br>"
      "                       Version 3, 29 June 2007<br>"
      "<br>"
      " Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/><br>"
      " Everyone is permitted to copy and distribute verbatim copies<br>"
      " of this license document, but changing it is not allowed.<br>"
      "<br>"
      "  This version of the GNU Lesser General Public License incorporates<br>"
      "the terms and conditions of version 3 of the GNU General Public<br>"
      "License, supplemented by the additional permissions listed below.<br>"
      "<br>"
      "  0. Additional Definitions.<br>"
      "<br>"
      "  As used herein, \"this License\" refers to version 3 of the GNU Lesser<br>"
      "General Public License, and the \"GNU GPL\" refers to version 3 of the GNU<br>"
      "General Public License.<br>"
      "<br>"
      "  \"The Library\" refers to a covered work governed by this License,<br>"
      "other than an Application or a Combined Work as defined below.<br>"
      "<br>"
      "  An \"Application\" is any work that makes use of an interface provided<br>"
      "by the Library, but which is not otherwise based on the Library.<br>"
      "Defining a subclass of a class defined by the Library is deemed a mode<br>"
      "of using an interface provided by the Library.<br>"
      "<br>"
      "  A \"Combined Work\" is a work produced by combining or linking an<br>"
      "Application with the Library.  The particular version of the Library<br>"
      "with which the Combined Work was made is also called the \"Linked<br>"
      "Version\".<br>"
      "<br>"
      "  The \"Minimal Corresponding Source\" for a Combined Work means the<br>"
      "Corresponding Source for the Combined Work, excluding any source code<br>"
      "for portions of the Combined Work that, considered in isolation, are<br>"
      "based on the Application, and not on the Linked Version.<br>"
      "<br>"
      "  The \"Corresponding Application Code\" for a Combined Work means the<br>"
      "object code and/or source code for the Application, including any data<br>"
      "and utility programs needed for reproducing the Combined Work from the<br>"
      "Application, but excluding the System Libraries of the Combined Work.<br>"
      "<br>"
      "  1. Exception to Section 3 of the GNU GPL.<br>"
      "<br>"
      "  You may convey a covered work under sections 3 and 4 of this License<br>"
      "without being bound by section 3 of the GNU GPL.<br>"
      "<br>"
      "  2. Conveying Modified Versions.<br>"
      "<br>"
      "  If you modify a copy of the Library, and, in your modifications, a<br>"
      "facility refers to a function or data to be supplied by an Application<br>"
      "that uses the facility (other than as an argument passed when the<br>"
      "facility is invoked), then you may convey a copy of the modified<br>"
      "version:<br>"
      "<br>"
      "   a) under this License, provided that you make a good faith effort to<br>"
      "   ensure that, in the event an Application does not supply the<br>"
      "   function or data, the facility still operates, and performs<br>"
      "   whatever part of its purpose remains meaningful, or<br>"
      "<br>"
      "   b) under the GNU GPL, with none of the additional permissions of<br>"
      "   this License applicable to that copy.<br>"
      "<br>"
      "  3. Object Code Incorporating Material from Library Header Files.<br>"
      "<br>"
      "  The object code form of an Application may incorporate material from<br>"
      "a header file that is part of the Library.  You may convey such object<br>"
      "code under terms of your choice, provided that, if the incorporated<br>"
      "material is not limited to numerical parameters, data structure<br>"
      "layouts and accessors, or small macros, inline functions and templates<br>"
      "(ten or fewer lines in length), you do both of the following:<br>"
      "<br>"
      "   a) Give prominent notice with each copy of the object code that the<br>"
      "   Library is used in it and that the Library and its use are<br>"
      "   covered by this License.<br>"
      "<br>"
      "   b) Accompany the object code with a copy of the GNU GPL and this license<br>"
      "   document.<br>"
      "<br>"
      "  4. Combined Works.<br>"
      "<br>"
      "  You may convey a Combined Work under terms of your choice that,<br>"
      "taken together, effectively do not restrict modification of the<br>"
      "portions of the Library contained in the Combined Work and reverse<br>"
      "engineering for debugging such modifications, if you also do each of<br>"
      "the following:<br>"
      "<br>"
      "   a) Give prominent notice with each copy of the Combined Work that<br>"
      "   the Library is used in it and that the Library and its use are<br>"
      "   covered by this License.<br>"
      "<br>"
      "   b) Accompany the Combined Work with a copy of the GNU GPL and this license<br>"
      "   document.<br>"
      "<br>"
      "   c) For a Combined Work that displays copyright notices during<br>"
      "   execution, include the copyright notice for the Library among<br>"
      "   these notices, as well as a reference directing the user to the<br>"
      "   copies of the GNU GPL and this license document.<br>"
      "<br>"
      "   d) Do one of the following:<br>"
      "<br>"
      "       0) Convey the Minimal Corresponding Source under the terms of this<br>"
      "       License, and the Corresponding Application Code in a form<br>"
      "       suitable for, and under terms that permit, the user to<br>"
      "       recombine or relink the Application with a modified version of<br>"
      "       the Linked Version to produce a modified Combined Work, in the<br>"
      "       manner specified by section 6 of the GNU GPL for conveying<br>"
      "       Corresponding Source.<br>"
      "<br>"
      "       1) Use a suitable shared library mechanism for linking with the<br>"
      "       Library.  A suitable mechanism is one that (a) uses at run time<br>"
      "       a copy of the Library already present on the user's computer<br>"
      "       system, and (b) will operate properly with a modified version<br>"
      "       of the Library that is interface-compatible with the Linked<br>"
      "       Version.<br>"
      "<br>"
      "   e) Provide Installation Information, but only if you would otherwise<br>"
      "   be required to provide such information under section 6 of the<br>"
      "   GNU GPL, and only to the extent that such information is<br>"
      "   necessary to install and execute a modified version of the<br>"
      "   Combined Work produced by recombining or relinking the<br>"
      "   Application with a modified version of the Linked Version. (If<br>"
      "   you use option 4d0, the Installation Information must accompany<br>"
      "   the Minimal Corresponding Source and Corresponding Application<br>"
      "   Code. If you use option 4d1, you must provide the Installation<br>"
      "   Information in the manner specified by section 6 of the GNU GPL<br>"
      "   for conveying Corresponding Source.)<br>"
      "<br>"
      "  5. Combined Libraries.<br>"
      "<br>"
      "  You may place library facilities that are a work based on the<br>"
      "Library side by side in a single library together with other library<br>"
      "facilities that are not Applications and are not covered by this<br>"
      "License, and convey such a combined library under terms of your<br>"
      "choice, if you do both of the following:<br>"
      "<br>"
      "   a) Accompany the combined library with a copy of the same work based<br>"
      "   on the Library, uncombined with any other library facilities,<br>"
      "   conveyed under the terms of this License.<br>"
      "<br>"
      "   b) Give prominent notice with the combined library that part of it<br>"
      "   is a work based on the Library, and explaining where to find the<br>"
      "   accompanying uncombined form of the same work.<br>"
      "<br>"
      "  6. Revised Versions of the GNU Lesser General Public License.<br>"
      "<br>"
      "  The Free Software Foundation may publish revised and/or new versions<br>"
      "of the GNU Lesser General Public License from time to time. Such new<br>"
      "versions will be similar in spirit to the present version, but may<br>"
      "differ in detail to address new problems or concerns.<br>"
      "<br>"
      "  Each version is given a distinguishing version number. If the<br>"
      "Library as you received it specifies that a certain numbered version<br>"
      "of the GNU Lesser General Public License \"or any later version\"<br>"
      "applies to it, you have the option of following the terms and<br>"
      "conditions either of that published version or of any later version<br>"
      "published by the Free Software Foundation. If the Library as you<br>"
      "received it does not specify a version number of the GNU Lesser<br>"
      "General Public License, you may choose any version of the GNU Lesser<br>"
      "General Public License ever published by the Free Software Foundation.<br>"
      "<br>"
      "  If the Library as you received it specifies that a proxy can decide<br>"
      "whether future versions of the GNU Lesser General Public License shall<br>"
      "apply, that proxy's public statement of acceptance of any version is<br>"
      "permanent authorization for you to choose that version for the<br>"
      "Library.";

  return license;
}
